custom scrollbar and contributions
codicocodes/speedtyper.dev pull request #100
Opened 2022-10-09 16:02 UTC by aditya-singh9

I have added custom scrollbar in the webpage and contributions section in the readme.

2022-10-09 17:43 UTC, codicocodes requested changes
Thank you for the contribution! I will look through and test this more later! 

But first of all the yarn.lock file should not be deleted!

2022-10-09 17:43 UTC, codicocodes commented on packages/webapp-next/yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Please do not remove the yarn lock, it should be persisted in the repository.

2022-10-09 17:53 UTC, aditya-singh9 commented on packages/webapp-next/yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Okay i will add this file

2022-10-09 18:28 UTC, aditya-singh9 commented on packages/webapp-next/yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Resolved

2022-10-11 20:05 UTC, codicocodes approved these changes

2022-10-11 20:07 UTC, merged