Added challenge info and cleaned code
codicocodes/speedtyper.dev pull request #106
Opened 2022-10-14 08:51 UTC by Ovoda

- Refactored Play2's component & file architecture
- Optimised & cleaned some code
- Added ChallengeInfo component  (see #90)

While adding challenge info to play2 to resolve issue #90, I noticed a lot of the front end code lacks proper architecture and is not optimised nor SEO friendly.

Let me know what you think of the architecture I implemented as an example of what can be done for the app. Any feedback is welcome.

2022-10-15 11:37 UTC, codicocodes requested changes
Thank you very much for the PR. I appreciate the time. And I really like the direction with splitting up components into smaller ones. :muscle: 

I do have some thoughts on the file structure, some other comments, and there are functional regressions with the added feature.

Please read through the comments and let me know if something is not clear.

2022-10-15 11:37 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +  const time = React.useMemo(
:exclamation: I don't think we have to `useMemo` on every function call. 

It can be worth it for performance, but I don't see either of these as expensive operations, they are both O(1). Consider it adds complexity to the code as well.

If the function returns a primitive value, such as a boolean or a string. Because primitive values are passed by value, not by reference, it means that they always remain the same anyway, even if the component is re-rendered.

2022-10-15 11:37 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +  const wpm = React.useMemo(() => cpmToWPM(cpm), [cpm]);
:art:  For reference, I prefer `useMemo` over `React.useMemo` generally for every hook.

2022-10-15 11:37 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayFooter/PlayFooter.tsx
> +export const PlayFooter: React.FC<PlayFooterProps> = (props) => {
I like extracting this to a separate component :+1: 

And generally I like that you split up components into smaller ones, great direction!

2022-10-15 11:37 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayerFooterChallengeInfo/PlayerFooterChallengeInfo.tsx
> +  PlayerFooterChallengeInfoProps
I don't think we need to have the `PlayFooter` prefix for every component that belong to the play footer. Is having it in the `play-footer` folder not enough?

Maybe for some components it's not a bad idea as it avoid very generic names. But if something already has a unique and understandable name I'm not sure if it adds value to couple the naming to the container. 

So just curious to get your thoughts.

2022-10-15 11:37 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayerFooterChallengeInfo/index.ts
> +export * from './PlayerFooterChallengeInfo'
There is some inconsistent naming between `Player` and `Play` we should be consistent on that.

2022-10-15 11:42 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +| Author : Calixte DE TOURRIS (Discord: Ovoda#3529)
Very good point, I agree with you. (Gotta change my file generator template ahah)

My thoughts with the name of the author was in case someone has a question on the component they knew who they could ask. This project being open source I don't think the need is present.

No headers ✅ 
No structure comments ✅

2022-10-15 12:04 UTC, codicocodes commented on packages/webapp-next/yarn.lock
> -"@eslint/eslintrc@^1.3.1":
I ran the build, and it seems like the build is failing due to the lock file being misconfigured

2022-10-15 12:20 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +export const PlayResults: React.FC<PlayResultsProps> = () => {
Side note: You can look at [this](https://github.com/codicocodes/speedtyper.dev/pull/97/commits/c4c7272519962b76d5222623125ea6a8f033f3e9) commit and see how much easier it is to review that commit since it only contains the moving of the files.

2022-10-15 20:04 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayerFooterChallengeInfo/PlayerFooterChallengeInfo.tsx
> +export const PlayerFooterChallengeInfo: React.FC<
I will check what's happening 👍

2022-10-15 20:08 UTC, Ovoda commented on packages/webapp-next/pages/play2.tsx
> +import { PlayFooter } from "../modules/play2/components/pages/play2/play-footer/PlayFooter";
The thought behind this is that eventually modules would be removed, making it just `components/pages/play2/play-footer/PlayFooter`. Yes I think a folder + index.ts + component.tsx per component is a nice structure (You HAVE to create shortcuts to create all these files or you'll spend hours creating them by hand, little tip)

Let's keep the module for now, I agree. However once we migrate we should replace the actual `/components` with the current `/modules/play2/components`. No need to keep modules in the future in my opinion.

2022-10-15 20:10 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +export const PlayResults: React.FC<PlayResultsProps> = () => {
I now think this commit as a test and a support for discussions and decisions about future changes, don't merge anything. I will re do every single thing following the "norme" we come up with, and also with nicely organised commits

Sorry for this mess, git is my nemesis lately

2022-10-15 20:17 UTC, Ovoda commented on packages/webapp-next/pages/play2.tsx
> -            <AnimatePresence>
Adding linting rules is going to be absolutely mandatory
[This](https://github.com/starton-io/eslint-config-nextjs) is what I've been using on my projects, it's quite sharp and might need to be tweaked for an open source project

I do however like sharp linting rules personally

2022-10-15 20:19 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayerFooterActions/PlayFooterActions.tsx
> +import { LinkIcon } from "../../../../../../../assets/icons/LinkIcon";
Absolutely, pretty easy to implement with NextJS I believe
I can take care of this in a future PR

2022-10-15 20:21 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayerFooterActions/PlayFooterActions.tsx
> +import { LinkIcon } from "../../../../../../../assets/icons/LinkIcon";
Awesome, yeah no need to do it now, just a note for a good future improvement

2022-10-15 20:27 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayerFooterChallengeInfo/PlayerFooterChallengeInfo.tsx
> +  PlayerFooterChallengeInfoProps
The idea on this is that if you have to change `PlayerFooterChallengeInfoActionButton` you know exactly where to find it just by its name: Player > Footer > ChallengeInfo > ActionButton.

It's mostly a productivity hack, as it allows anyone to find anything pretty quickly without knowing the code/components architecture.

Helps in IDE tabs too, if multiple files have the same name it can get confusing.

I think we could find a simple set of rules that could get the best from both worlds.

2022-10-15 20:29 UTC, Ovoda commented on packages/webapp-next/yarn.lock
> -"@eslint/eslintrc@^1.3.1":
I played a little bit with the package.json but pretty sure I didn't change anything.
As explained in a future comment, don't merge my little mess ^^

2022-10-15 20:34 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +  const wpm = React.useMemo(() => cpmToWPM(cpm), [cpm]);
Just a personal preference on my side.
We need to make sure to only use one so let's use your method, `useMemo` instead of `React.useMemo` ✅

2022-10-15 20:35 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayFooter/PlayFooter.tsx
> +export const PlayFooter: React.FC<PlayFooterProps> = (props) => {
Let's take this direction then ^^ ✅

2022-10-16 07:21 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +  const time = React.useMemo(
This one is my bad

2022-10-16 07:24 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +| Author : Calixte DE TOURRIS (Discord: Ovoda#3529)
Just had another thought about this, even if we don’t use comments to structure our files, I think it’s important to always follow the same order when creating one.
I’d suggest imports > contracts (interfaces, types, enum,etc…) > utils (until function, context, objects…) > sub components > component

2022-10-16 08:59 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +| Author : Calixte DE TOURRIS (Discord: Ovoda#3529)
:thinking: I'm not planning on using the term 'contracts'. I will probably think about it, but it's not a plan at this point. 

I typically want to have the types as close to the relevant component as possible. Having a file for each type of type, does  not seem valuable to me at this scale. Or maybe I don't understand this comment?

I think the best is to not get bogged down in discussions about the best file structure. Instead try to follow the already existing structure of the project but do improvements within that structure: 

1. name space by feature / container, e.g. like you suggested with `play-footer/Timer/Timer.tsx`
2. split into smaller components

The structure can always be reevaluated if we see problems with it, but at this point I think just following the current structure is the best way forward.

2022-10-16 09:02 UTC, codicocodes commented on packages/webapp-next/pages/play2.tsx
> +import { PlayFooter } from "../modules/play2/components/pages/play2/play-footer/PlayFooter";
I have not decided to migrate to that structure, see [this](https://github.com/codicocodes/speedtyper.dev/pull/106#discussion_r996412458) comment. 

We can always decide to change later, but at this point I think it's not the most important thing to think about.

2022-10-16 09:08 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/play-footer/PlayerFooterChallengeInfo/PlayerFooterChallengeInfo.tsx
> +  PlayerFooterChallengeInfoProps
I don't really navigate like this, I use my LSP and navigate with `go to definition` or `find references` if I am on the actual component. If the folders are name spaced, grepping for `footer challenge button` is also a fast way to get there.

I see it as something we can use sparingly if there are multiple files with the same name. I see the value in this case. But we shouldn't default to it.

2022-10-16 09:12 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +export const PlayResults: React.FC<PlayResultsProps> = () => {
Don't worry about the git stuff! I'm just trying to show the value of a cleaner git history.

But getting better at git will make you a stronger developer, and will make it easier to review PR's. A tip is to get good at `amend` and `rebase`.

2022-10-16 10:35 UTC, codicocodes commented on packages/webapp-next/pages/play2.tsx
> -            <AnimatePresence>
Linting rules are great because they prevent discussions about those things in PR's. We already have eslint-config-next, I believe next scaffold ships with it.

There is a ticket here for adding the specific linting rule: https://github.com/codicocodes/speedtyper.dev/issues/84

Maybe it can be configured already with eslint-config-next, so adding the plugin would then be unnecessary

2022-10-16 12:35 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +| Author : Calixte DE TOURRIS (Discord: Ovoda#3529)
I suggest starting with smaller refactoring, and features, and as you contribute more I will trust your more as well, and you will have more freedom to add larger features, larger refactorings and improvements.

I reflected on these discussions a bit, and it's quite time consuming. From my perspective it's high risk activity because I am spending a lot of time discussing file structure to make it easier for you to contribute, but I also don't know how much you will be contributing in the end, and I am unsure how much value the proposed architecture will give me in the future.

You being opinionated is a good thing :+1: But every contributor jumping on will not be able to have the architecture the way that they prefer, and I think for me to have this discussion with every contributor is not scalable or valuable. 

While having an opinion is a good thing, being able to effectively work in another architecture and style that does not fit your ideal and make incremental improvements to that is a valuable skill to have.

I do still take your thoughts into consideration for sure and I appreciate the initiative, and will continue to reflect on the file structure and overall architecture. But for now I do not want to commit to large changes.

Your impact is definitely there though in terms of name spacing by feature, e.g. `play-footer`. This is an improvement I am willing to commit to right now. It would be great to see a small example of just the footer fitting into the current modules structure.

Do my thoughts makes sense from your perspective?

Something like this is how I vision the current architecture looking:

```
/src
    /common
        /components
            /Button
        /hooks
            /use-hooks-hook
        /utils
            /time
                /toHumanReadableTime
        /services
        /stores
    /modules
        /play2
            /components
                /game-header
                /code-area
                /game-footer
                    /GameFooter
                    /GameTimer
                    /GameActions
                        GameActions.spec.ts
                        GameActions.storybook.ts
                        GameActions.types.ts
                        GameActions.tsx
                        index.ts
            /hooks
            /services
            /stores
```

Of course it's not written in stone, but I'd like to keep going with this, with incremental improvements, and see what the bottle necks are before deciding on large changes.

Thank you for interesting discussions though. These are just some reflections. :thinking:

2022-10-16 12:48 UTC, codicocodes commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +| Author : Calixte DE TOURRIS (Discord: Ovoda#3529)
There is definitely an opportunity for contributors to take more ownership and initiative on the front end. 

It's partly on me to as quickly as possible make progress with the rewrite and make it stable. 

And then partly it's just a matter of time and smaller contributions adding up, and building trust throughout that process.

2022-10-16 19:55 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +| Author : Calixte DE TOURRIS (Discord: Ovoda#3529)
Okay, yes I understand. My goal is not to take all of your time ^^
This is not really what I meant (about your first comment), but it doesn't matter.

I agree that was time consuming, even tho I enjoyed the different ideas and opinions, so let's stop here.
I will now fix current issues and do some PR ;)

2022-10-16 19:56 UTC, Ovoda commented on packages/webapp-next/modules/play2/components/pages/play2/PlayResults/PlayResults.tsx
> +export const PlayResults: React.FC<PlayResultsProps> = () => {
✅

2022-10-17 05:55 UTC, closed without merging