Extract reusable button component
codicocodes/speedtyper.dev pull request #62
Opened 2022-09-24 20:15 UTC by Alcherith

2022-09-25 08:27 UTC, codicocodes commented
@Alcherith There are some conflicts with your other PR which I just merged, could you rebase on main and solve the conflicts?

2022-09-25 08:56 UTC, codicocodes requested changes
Great job @Alcherith and thank you so much for the help on this.

I have some change suggestions, would be happy to pair on them when you have the chance. 

Do rebase on main when you have the chance as well as there are some conflicts due to your previous PR.

2022-09-25 08:56 UTC, codicocodes commented on packages/webapp-next/components/Button.tsx
> +            type="button"
:exclamation: Could we run Prettier on all files? it's not formatted, IDK why linting passed :sweat_smile: I think I did not add `eslint/prettier` as a rule on the frontend :rofl:

2022-09-25 08:56 UTC, codicocodes commented on packages/webapp-next/components/Button.tsx
> +    if (color === "primary") {
:exclamation: I don't think we should need this if statement, the only difference should be the colors in the `css` right. 
 
This if statement leads to harder to read code and some inconsistencies already due to size not being managed for `secondary` button.

 We want to have the designs to be as universal as possible, and the color you pass down have should only affect the color of the button. I think we can probably align this more.

I'm happy to pair on this if you want!

2022-09-25 08:56 UTC, codicocodes commented on packages/webapp-next/components/Button.tsx
> +        type="button"
:question:  Disabled is not being passed into the button here? I think it needs to be passed down in order to actually disable the button right?

2022-09-25 08:56 UTC, codicocodes commented on packages/webapp-next/components/LanguageDropdown.tsx
> +  const DownArrowIcon = () => {
:question: Were you planning on moving the icons to separate files in a separate PR. It would be OK to do it in this one if you would like, up to you.

2022-09-25 08:56 UTC, codicocodes commented on packages/webapp-next/components/Button.tsx
> +    size?: "lg",
:question: Maybe we can make this into `"md" | "lg"` and then default it to medium with `{ size = "md" }`? It would make it easier to add other sizes if we wanted to.

2022-09-25 08:56 UTC, codicocodes commented on packages/webapp-next/components/Button.tsx
> +        className={`flex my-4 items-center ${disabled ? "cursor-not-allowed" : "hover:bg-purple-300 cursor-pointer"} bg-purple-400 py-2 px-4 ml-4 rounded shadow-2xl border-gray-200 border`}
:exclamation: Another issue with having the if statement is that this button is missing the `title`

2022-09-25 08:56 UTC, codicocodes commented on packages/webapp-next/components/Button.tsx
> +    onClick?: any,
:question: Is this the only missing type? We should specify that it's a function at least with `(event: any) => void` or we can try to use `(event: React.MouseEvent<HTMLButtonElement>) => void` as well.

Right now you can pass down a string as `onClick` and it would not fail at compile time, instead lead to a runtime error, it would be nice to have some TS protection here.

2022-09-25 13:32 UTC, abrigoni commented on packages/webapp-next/components/Button.tsx
> +    onClick?: any,
I think the prop type for this component can extend the button component prop's so the only new prop will be color, disabled and onClick will come directly from the button. Like this: 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/25093044/192146152-3162dd56-b15c-4d6c-b65e-6126e16965d4.png">

This way the onClick prop grabs the same as any reactjs <button> tag.

2022-09-25 19:16 UTC, Alcherith commented on packages/webapp-next/components/Button.tsx
> +            type="button"
Yes

2022-09-26 17:51 UTC, codicocodes commented
It's currently showing the wrong logo on the Contribute button. 

![image](https://user-images.githubusercontent.com/76068197/192344826-0ff7a84b-994d-4f4c-911d-f31c364b82a6.png)

These two buttons are not aligned, they are a couple of pixels off. Originally they were also off I think, but a little bit less than this.

![image](https://user-images.githubusercontent.com/76068197/192345179-2e9ac055-7981-42bd-b1b8-90b46cfbd247.png)

2022-09-26 17:53 UTC, codicocodes commented on packages/webapp-next/components/Button.tsx
> +        "text-base py-1.5 px-2"
Can we use: `"text-base py-2 px-4"` here?

`py-1.5` is not a valid tailwind class, so this ends up looking a bit off.

![image](https://user-images.githubusercontent.com/76068197/192346431-7dc43c62-08e2-4b0f-a153-26812e7b54b5.png)

With updated styles it would look like this:

![image](https://user-images.githubusercontent.com/76068197/192346508-853394a0-42ea-445e-9bfd-b4e88aa68f7c.png)

2022-09-26 17:55 UTC, codicocodes requested changes
Just tiny things left:
- md size classes are wrong
- showing the wrong icon on contribute button
- contribute and join discord button are misaligned (this was already a problem, so we can break it out into a separate ticket)

2022-09-26 19:11 UTC, codicocodes approved these changes
Thank you for the help with this!

2022-09-26 19:11 UTC, merged