issue no #68 by saksham
codicocodes/speedtyper.dev pull request #69
Opened 2022-09-25 13:20 UTC by ronakmehtav

The copy is used for copy link to invite friends.

2022-09-25 17:54 UTC, codicocodes requested changes

2022-09-25 17:54 UTC, codicocodes commented on packages/webapp-next/pages/index.tsx
> +                <p className="pl-2">Invite Friends</p>
Thanks for the issue and the PR. Unfortunately you changed the wrong button.

You probably want to look at the `ShareRaceButton`. Feel free to address it, otherwise I might look at this later.

![image](https://user-images.githubusercontent.com/76068197/192157772-e69e15ae-16a8-40f8-b4a5-d7aa4b56c298.png)

2022-09-26 05:56 UTC, ronakmehtav commented on packages/webapp-next/pages/index.tsx
> +                <p className="pl-2">Invite Friends</p>
I don't think so the issue saksham raised had these copy button only. In the play section.

2022-09-26 05:59 UTC, ronakmehtav commented on packages/webapp-next/pages/index.tsx
> +                <p className="pl-2">Invite Friends</p>
![image](https://user-images.githubusercontent.com/31774137/192203696-91a74277-361f-41f0-8681-e9c2556e3e58.png)

2022-09-26 05:59 UTC, ronakmehtav commented on packages/webapp-next/pages/index.tsx
> +                <p className="pl-2">Invite Friends</p>
ok  I ll change it.

2022-09-26 06:33 UTC, ronakmehtav commented on packages/webapp-next/pages/index.tsx
> +                <p className="pl-2">Invite Friends</p>
Done it.

2022-09-27 14:48 UTC, ronakmehtav commented
updated the code with consideration of latest button changes

2022-09-27 18:36 UTC, codicocodes approved these changes
Thank you very much for the help @ronakmehtav 

Next time, please squash the commits if you have commits in non working states, and use messages in imperative form. 

Nice improvement :+1:

2022-09-27 18:37 UTC, merged