Added Eslint Plugin Prettier to webapp-next directory
codicocodes/speedtyper.dev pull request #79
Opened 2022-09-27 07:39 UTC by Murad013

🚀 Description

Added Eslint Plugin Prettier to webapp-next directory

2022-09-27 07:47 UTC, ronakmehtav commented
does it not give any linting issue ?

2022-09-27 07:55 UTC, ronakmehtav commented
> you haven't added the prettier to eslint rc. please modify it.

and eslint-prettier plugin should be dev dependency should it not ?

2022-09-27 07:56 UTC, ronakmehtav commented
> 🚀 Description
> 
> Added Eslint Plugin Prettier to webapp-next directory
- please modify the eslint config appropriately.
- please add the eslint plugin as dev dependency.

2022-09-27 08:09 UTC, Murad013 commented
Hey @ronakmehtav I'm pretty sure I've made the proper changes. Please check them out at your earliest convenience and thank you for your patience!

2022-09-27 08:25 UTC, ronakmehtav commented
> Hey @ronakmehtav I'm pretty sure I've made the proper changes. Please check them out at your earliest convenience and thank you for your patience!

the eslint are already under devdependency only so add the prettier plugin dev dependency.

2022-09-27 08:29 UTC, ronakmehtav commented
> Hey @ronakmehtav I'm pretty sure I've made the proper changes. Please check them out at your earliest convenience and thank you for your patience!

and have you run next build to catch any error's 
link : https://nextjs.org/docs/basic-features/eslint

2022-09-27 08:44 UTC, ronakmehtav commented
> Hey @ronakmehtav I'm pretty sure I've made the proper changes. Please check them out at your earliest convenience and thank you for your patience!

you forgot to add prettier plugin

2022-09-27 08:52 UTC, ronakmehtav commented
> Hey @ronakmehtav I'm pretty sure I've made the proper changes. Please check them out at your earliest convenience and thank you for your patience!

@Murad013  also you 'll have to create prettier config file. Ask @codicocodes  about the rules he want's on the prettier config.

2022-09-27 18:27 UTC, codicocodes requested changes
Thank you so much for the help @Murad013 

There are a couple of issues before we can merge this PR, please have a look!

2022-09-27 18:27 UTC, codicocodes commented on packages/webapp-next/package-lock.json
> +{
Please remove `package-lock.json`, speedtyper.dev uses yarn

2022-09-27 18:27 UTC, codicocodes commented on packages/webapp-next/yarn.lock
> -  version "7.18.9"
Please run `yarn` to ensure yarn.lock is up to date, when running yarn on this branch there are a lot of diffs.

2022-09-29 09:39 UTC, codicocodes commented
@Murad013 I think we should go without a prettier config, if we don't have any custom rules and if it's not necessary.

Currently build is failing because the prettier config is empty. I also expect the build to fail due to unaddressed prettier issues even after that. (Just running prettier on all erroring files should suffice)

2022-09-29 10:12 UTC, codicocodes commented on packages/webapp-next/.prettierrc.json
> +��
This file needs to be removed or a valid config should be added. I think we can remove the config file and go with default config for now.

2022-09-29 12:23 UTC, Murad013 commented
I rebased on main but I'm not sure what to do next 😅

2022-09-29 14:26 UTC, codicocodes commented
> I rebased on main but I'm not sure what to do next 😅

1. First you need to make sure your main is up to date.
2. `git rebase main` -> this should cause conflicts
3. Solve the conflicts
4. force push

2022-09-29 16:35 UTC, codicocodes approved these changes
Thank you for the help @Murad013

2022-09-29 16:36 UTC, merged